### ISSUE TITLE
Error with type = "osm-bw"

### ISSUE THREAD

**Issue by Robinlovelace** [mtennekes/tmap#38]
This errors:

```
b <- bb("Hereford")
hf <- read_osm(x = b, minNumTiles = 5, type = "osm-bw")
```

This is OK though:

```
b <- bb("Hereford")
hf <- read_osm(x = b, minNumTiles = 5, type = "osm")
```

Same problem if you replace `Hereford` with `New York`.

Error message:

```
java.lang.NullPointerException
	at edu.cens.spatial.RTileController.getTileValues(RTileController.java:117)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at RJavaTools.invokeMethod(RJavaTools.java:386)
Error in osmtile(x, y, zoom, type) : could not obtain tile: 300 384 10
```

**Comment by Robinlovelace** [comment]
Apologies - this seems to be an OpenStreetMap issue:

``openmap(c(43.46886761482925,119.94873046875),
 		c(33.22949814144951,133.9892578125),
		minNumTiles=4, type = "osm-bw")
java.lang.NullPointerException ...
```
